services:
  mysql:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - django-network  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s  


  django:
    build: .
    container_name: django_app

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      mysql:
        condition: service_healthy

    command: python manage.py runserver 0.0.0.0:8000

    networks:
      - django-network
  



volumes:
  mysql_data:

networks:
   django-network:  
